# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa12db71624fedb5acdba6e21a383dc67ffc8a36e39d42187e2b5e6245baec42a2d96bef779274074d5ac9f5c93da8b18cd680a49cd54c765b5d8e5553987960

test:
  secret_key_base: 8569415bdf4029355d15024cfdc4a01fd18cd7663af705fe2a6a5121852bec32ecb5ab8d028fb24ce559aebd52500698a201022a8b53453cfab7d1c8592388da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
